name: POLR
favicon: null
layout_spectrum: 0.08626086497679353
typography_spectrum: 0.3336154178250581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9499438963830471
  lightness: 0.2719482097309083
  saturation: 0.4635659682098776
  rhythmicContrast: 0.7444612528197467
purpose: []
