name: POLR
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39013
title: Path Of Least Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#54af0b'
    - '#3b7a07'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
