name: POLR
favicon: null
layout_spectrum: 0.27892
typography_spectrum: 0.5046
title: Path Of Least Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#54af0b'
    - '#3b7a07'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.9499438963830471
  lightness: 0.2719482097309083
  saturation: 0.4635659682098776
  rhythmicContrast: 0.7444612528197467
purpose: []
